import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/header";
import { Sidebar } from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="min-h-screen flex flex-col">
            <div className=" ">
              <Header />
            </div>
            <div className="relative flex flex-grow">
              <nav className="bg-white shadow-sm p-6 space-y-6 w-64 hidden md:block">
                <Sidebar />
              </nav>
              <main className="bg-gray-100 flex-1 p-6 "> {children} </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
