export const data = [
  {
    image: "https://example.com/image1.jpg",
    variants: ["Red", "Blue", "Green"],
    sku: "ABC123",
    category: "Electronics",
    stock: 15,
    price: 199.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image2.jpg",
    variants: ["Small", "Medium", "Large"],
    sku: "DEF456",
    category: "Clothing",
    stock: 30,
    price: 49.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image3.jpg",
    variants: ["Black", "White"],
    sku: "GHI789",
    category: "Accessories",
    stock: 5,
    price: 15.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image4.jpg",
    variants: ["One Size"],
    sku: "JKL012",
    category: "Home",
    stock: 12,
    price: 39.99,
    name: "demo",
    date: "01-12-2024",
    status: "Draft",
  },
  {
    image: "https://example.com/image5.jpg",
    variants: ["Small", "Medium"],
    sku: "MNO345",
    category: "Sports",
    stock: 50,
    price: 29.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image6.jpg",
    variants: ["Gold", "Silver"],
    sku: "PQR678",
    category: "Jewelry",
    stock: 8,
    price: 149.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image7.jpg",
    variants: ["Red", "Yellow"],
    sku: "STU901",
    category: "Toys",
    stock: 20,
    price: 19.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image8.jpg",
    variants: ["32GB", "64GB"],
    sku: "VWX234",
    category: "Electronics",
    stock: 25,
    price: 99.99,
    name: "demo",
    date: "01-12-2024",
    status: "Draft",
  },
  {
    image: "https://example.com/image9.jpg",
    variants: ["Blue", "Black"],
    sku: "YZA567",
    category: "Footwear",
    stock: 60,
    price: 39.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image10.jpg",
    variants: ["Small", "Large"],
    sku: "BCD890",
    category: "Furniture",
    stock: 18,
    price: 129.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image11.jpg",
    variants: ["Black", "White", "Grey"],
    sku: "EFG123",
    category: "Appliances",
    stock: 10,
    price: 299.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image12.jpg",
    variants: ["1L", "500ml"],
    sku: "HIJ456",
    category: "Beauty",
    stock: 40,
    price: 24.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image13.jpg",
    variants: ["Small", "Medium"],
    sku: "KLM789",
    category: "Books",
    stock: 35,
    price: 15.99,
    name: "demo",
    date: "01-12-2024",
    status: "Draft",
  },
  {
    image: "https://example.com/image14.jpg",
    variants: ["Red", "Black"],
    sku: "NOP012",
    category: "Gaming",
    stock: 45,
    price: 89.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image15.jpg",
    variants: ["Large", "Small"],
    sku: "QRS345",
    category: "Pets",
    stock: 10,
    price: 59.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image16.jpg",
    variants: ["Black", "Brown"],
    sku: "TUV678",
    category: "Furniture",
    stock: 15,
    price: 249.99,
    name: "demo",
    date: "01-12-2024",
    status: "Draft",
  },
  {
    image: "https://example.com/image17.jpg",
    variants: ["Small", "Medium"],
    sku: "WXY901",
    category: "Electronics",
    stock: 32,
    price: 159.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image18.jpg",
    variants: ["Large", "Extra Large"],
    sku: "ZAB234",
    category: "Sports",
    stock: 60,
    price: 49.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image19.jpg",
    variants: ["Small", "Medium", "Large"],
    sku: "CDE567",
    category: "Fashion",
    stock: 70,
    price: 99.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image20.jpg",
    variants: ["Blue", "Red"],
    sku: "FGH890",
    category: "Accessories",
    stock: 20,
    price: 24.99,
    name: "demo",
    date: "01-12-2024",
    status: "Draft",
  },
  {
    image: "https://example.com/image21.jpg",
    variants: ["XL", "XXL"],
    sku: "IJK123",
    category: "Toys",
    stock: 80,
    price: 14.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image22.jpg",
    variants: ["Large", "Small"],
    sku: "LMN456",
    category: "Beauty",
    stock: 10,
    price: 199.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image23.jpg",
    variants: ["Pink", "Purple"],
    sku: "OPQ789",
    category: "Furniture",
    stock: 25,
    price: 49.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image24.jpg",
    variants: ["Black", "White"],
    sku: "RST012",
    category: "Electronics",
    stock: 12,
    price: 199.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image25.jpg",
    variants: ["Large", "Small"],
    sku: "UVW345",
    category: "Toys",
    stock: 90,
    price: 29.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image26.jpg",
    variants: ["Red", "Black"],
    sku: "XYZ678",
    category: "Home",
    stock: 15,
    price: 199.99,
    name: "demo",
    date: "01-12-2024",
    status: "Draft",
  },
  {
    image: "https://example.com/image27.jpg",
    variants: ["Medium", "Large"],
    sku: "ABC234",
    category: "Electronics",
    stock: 50,
    price: 89.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
  {
    image: "https://example.com/image28.jpg",
    variants: ["Gold", "Silver"],
    sku: "DEF567",
    category: "Jewelry",
    stock: 8,
    price: 249.99,
    name: "demo",
    date: "01-12-2024",
    status: "Low stock",
  },
  {
    image: "https://example.com/image29.jpg",
    variants: ["Black", "Brown"],
    sku: "GHI890",
    category: "Footwear",
    stock: 25,
    price: 79.99,
    name: "demo",
    date: "01-12-2024",
    status: "Draft",
  },
  {
    image: "https://example.com/image30.jpg",
    variants: ["Red", "Blue"],
    sku: "JKL012",
    category: "Books",
    stock: 10,
    price: 9.99,
    name: "demo",
    date: "01-12-2024",
    status: "Published",
  },
];
